### Recommendations with MovieTweetings: Getting to Know The Data

Throughout this lesson, you will be working with the [MovieTweetings Data](https://github.com/sidooms/MovieTweetings/tree/master/recsyschallenge2014).

**Note:** There are solutions to each of the notebooks available by hitting the orange jupyter logo in the top left of this notebook.  Additionally, you can watch me work through the solutions on the screencasts that follow each workbook. 

To get started, read in the libraries and the two datasets you will be using throughout the lesson using the code below.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tests as t

%matplotlib inline


# Read in the MovieTweetings dataset originally taken from https://github.com/sidooms/MovieTweetings/tree/master/latest
movies = pd.read_csv('movies.dat', delimiter='::', header=None, names=['movie_id', 'movie', 'genre'], dtype={'movie_id': object}, engine='python')
reviews = pd.read_csv('ratings.dat', delimiter='::', header=None, names=['user_id', 'movie_id', 'rating', 'timestamp'], dtype={'movie_id': object, 'user_id': object, 'timestamp': object}, engine='python')

In [2]:
movies.head()

,movie_id,movie,genre
0,0000008,Edison Kinetoscopic Record of a Sneeze (1894),Documentary|Short
1,0000010,La sortie des usines Lumière (1895),Documentary|Short
2,0000012,The Arrival of a Train (1896),Documentary|Short
3,25,The Oxford and Cambridge University Boat Race ...,NaN
4,0000091,Le manoir du diable (1896),Short|Horror

In [3]:
reviews.head()

  user_id  movie_id  rating   timestamp
0       1   0114508       8  1381006850
1       2   0208092       5  1586466072
2       2   0358273       9  1579057827
3       2  10039344       5  1578603053
4       2   6751668       9  1578955697

#### 1. Take a Look At The Data 

Take a look at the data and use your findings to fill in the dictionary below with the correct responses to show your understanding of the data.

In [4]:
# cell for work
movie_num = movies.shape[0]

In [5]:
# cell for work
rating_num = reviews[~reviews['rating'].isnull()].shape[0]

In [6]:
missingrating_num = reviews[reviews['rating'].isnull()].shape[0]

In [7]:
# more work
genre_num = len(movies['genre'].value_counts())

In [8]:
user_num = len(reviews['user_id'].value_counts())

In [9]:
# and still more
rating_avg = reviews['rating'].mean()

In [10]:
rating_min = reviews['rating'].min()

In [11]:
# and even more - open additional cells as necessary
rating_max = reviews['rating'].max()

In [12]:
# Use your findings to match each variable to the correct statement in the dictionary


dict_sol1 = {
'The number of movies in the dataset': movie_num,
'The number of ratings in the dataset': rating_num,
'The number of different genres': genre_num,
'The number of unique users in the dataset': user_num,
'The number missing ratings in the reviews dataset': missingrating_num,
'The average rating given across all ratings': rating_avg,
'The minimum rating given across all ratings': rating_min,
'The maximum rating given across all ratings': rating_max
}

# Originally, I had this to check your solution, but the 
# links are live and updating.  That didn't end up being
# a great idea

In [13]:
dict_sol1

{'The number of movies in the dataset': 35479,
 'The number of ratings in the dataset': 863866,
 'The number of different genres': 2736,
 'The number of unique users in the dataset': 67353,
 'The number missing ratings in the reviews dataset': 0,
 'The average rating given across all ratings': 7.3158776939942074,
 'The minimum rating given across all ratings': 0,
 'The maximum rating given across all ratings': 10}

#### 2. Data Cleaning

Next, we need to pull some additional relevant information out of the existing columns. 

For each of the datasets, there are a couple of cleaning steps we need to take care of:

#### Movies
* Pull the date from the title and create new column
* Dummy the date column with 1's and 0's for each century of a movie (1800's, 1900's, and 2000's)
* Dummy column the genre with 1's and 0's

#### Reviews
* Create a date out of time stamp

You can check your results against the header of my solution by running the cell below with the **show_clean_dataframes** function.

In [16]:
# and another
def date(df):
    date_list = []
    for x in df['movie']:
        date = int(x.split('(')[1][0:4])
        if date < 1900:
            date_list.append("1800's")
        elif date < 2000:
            date_list.append("1900's")
        else:
            date_list.append("2000's")
    df['date'] = date_list
    return df

In [17]:
movies = date(movies)

In [20]:
movies['date'].tail()

35474    2000's
35475    2000's
35476    2000's
35477    2000's
35478    2000's
Name: date, dtype: object

In [22]:
pd.get_dummies(movies['date'])

       1800's  1900's  2000's
0           1       0       0
1           1       0       0
2           1       0       0
3           1       0       0
4           1       0       0
5           1       0       0
6           0       1       0
7           0       1       0
8           0       1       0
9           0       1       0
10          0       1       0
11          0       1       0
12          0       1       0
13          0       1       0
14          0       1       0
15          0       1       0
16          0       1       0
17          0       1       0
18          0       1       0
19          0       1       0
20          0       1       0
21          0       1       0
22          0       1       0
23          0       1       0
24          0       1       0
25          0       1       0
26          0       1       0
27          0       1       0
28          0       1       0
29          0       1       0
...       ...     ...     ...
35449       0       0       1
35450       0       0       1
35451       0       0       1
35452       0       0       1
35453       0       0       1
35454       0       0       1
35455       0       0       1
35456       0       0       1
35457       0       0       1
35458       0       0       1
35459       0       0       1
35460       0       0       1
35461       0       0       1
35462       0       0       1
35463       0       0       1
35464       0       0       1
35465       0       0       1
35466       0       0       1
35467       0       0       1
35468       0       0       1
35469       0       0       1
35470       0       0       1
35471       0       0       1
35472       0       0       1
35473       0       0       1
35474       0       0       1
35475       0       0       1
35476       0       0       1
35477       0       0       1
35478       0       0       1

[35479 rows x 3 columns]

In [23]:
pd.get_dummies(movies['genre'])

,Action,Action|Adventure,Action|Adventure|Biography,Action|Adventure|Biography|Crime|Drama,Action|Adventure|Biography|Crime|History|Romance|Western,Action|Adventure|Biography|Drama,Action|Adventure|Biography|Drama|History,Action|Adventure|Biography|Drama|History|Romance,Action|Adventure|Biography|Drama|History|Romance|War,Action|Adventure|Biography|Drama|History|Thriller,...,Thriller|Western,War,War|Drama,War|Western,Western,Western|Adventure|Comedy,Western|Comedy,Western|Drama,Western|Fantasy,Western|Horror
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35449,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35450,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35451,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35452,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35453,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35454,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35455,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35456,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35457,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35458,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35459,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35460,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35461,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35462,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35463,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35464,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35465,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35466,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35467,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35468,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35469,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35470,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35471,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35472,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35473,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35474,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35475,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35476,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35477,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35478,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
reviews_new, movies_new = t.show_clean_dataframes()

   Unnamed: 0  user_id  movie_id  rating   timestamp                 date  \
0           0        1     68646      10  1381620027  2013-10-12 23:20:27
1           1        1    113277      10  1379466669  2013-09-18 01:11:09
2           2        2    422720       8  1412178746  2014-10-01 15:52:26
3           3        2    454876       8  1394818630  2014-03-14 17:37:10
4           4        2    790636       7  1389963947  2014-01-17 13:05:47

   month_1  month_2  month_3  month_4    ...      month_9  month_10  month_11  \
0        0        0        0        0    ...            0         1         0
1        0        0        0        0    ...            0         0         0
2        0        0        0        0    ...            0         1         0
3        0        0        0        0    ...            0         0         0
4        0        0        0        0    ...            0         0         0

   month_12  year_2013  year_2014  year_2015  year_2016  year_2017  year_2018
0         0          1          0          0          0          0          0
1         0          1          0          0          0          0          0
2         0          0          1          0          0          0          0
3         0          0          1          0          0          0          0
4         0          0          1          0          0          0          0

[5 rows x 24 columns]
   Unnamed: 0  movie_id                                              movie  \
0           0         8      Edison Kinetoscopic Record of a Sneeze (1894)
1           1        10                La sortie des usines Lumière (1895)
2           2        12                      The Arrival of a Train (1896)
3           3        25  The Oxford and Cambridge University Boat Race ...
4           4        91                         Le manoir du diable (1896)

               genre  date  1800's  1900's  2000's  History  News    ...     \
0  Documentary|Short  1894       1       0       0        0     0    ...
1  Documentary|Short  1895       1       0       0        0     0    ...
2  Documentary|Short  1896       1       0       0        0     0    ...
3                NaN  1895       1       0       0        0     0    ...
4       Short|Horror  1896       1       0       0        0     0    ...

   Fantasy  Romance  Game-Show  Action  Documentary  Animation  Comedy  Short  \
0        0        0          0       0            1          0       0      1
1        0        0          0       0            1          0       0      1
2        0        0          0       0            1          0       0      1
3        0        0          0       0            0          0       0      0
4        0        0          0       0            0          0       0      1

   Western  Thriller
0        0         0
1        0         0
2        0         0
3        0         0
4        0         0

[5 rows x 36 columns]